---
title: "MATH 3070 Lab Fall Project 1"
author: "Ishaan Rajan"
date: "September 3, 2020"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
---



## Problem 1 (Verzani problem 1.1)
*Use R as you would a calculator to find numeric answers to the following:*

1. $1 + 2(3 + 4)$

```{r, tidy=TRUE, error=TRUE}
(1 + (2*(3+4)))
```

2. $4^3 + 3^{2 + 1}$

```{r, tidy=TRUE, error=TRUE}
((4^3) + 3^(2+1))
```

3. $\sqrt{(4 + 3)(2 + 1)}$

```{r, tidy=TRUE, error=TRUE}
sqrt((4+3)*(2+1))
```

4. $\left(\frac{1+2}{3 + 4} \right)^2$

```{r, tidy=TRUE, error=TRUE}
 ((1+2)/(3+4))^2
```

## Problem 2 (Verzani problem 1.4)
*Use R to compute the following:*

$$\frac{0.25 - 0.2}{\sqrt{0.2(1-0.2)/100}}$$

```{r, tidy=TRUE, error=TRUE}
((0.25-0.2)/sqrt((0.2*(1-0.2))/100))

```

## Problem 3 (Verzani problem 1.7)
*The `exec.pay` (**UsingR**) data set is available after loading the package **UsingR**. Load the package, and inspect the data set. Scan the values to find the largest one.*

```{r, tidy=TRUE, error=TRUE}
x = UsingR::exec.pay
max(x)
```
